name: hydraccobadges
description: "Rewarding hydration"
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  flutter_svg: ^2.0.17
  flutter_animate: ^4.5.2
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
  
  module:
    androidX: true
    androidPackage: com.marcosanna.hydracco
    iosBundleIdentifier: com.marcosanna.hydracco
